run:
  timeout: 60m
  skip-dirs:
    - hack/($|/)
    - (^|/)vendor($|/)
    - (^|/)generated($|/)
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - whitespace
    - bodyclose
    - dupl
    - errcheck
    - gci
    - gofmt
    - goimports
    - misspell
    - unused
    - typecheck
linters-settings:
  goimports:
    local-prefixes: github.com/kosmos.io/clusterlink
  misspell:
    ignore-words:
      - creater
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/kosmos.io/clusterlink)
output:
  sort-results: true




