apiVersion: v1
kind: Service
metadata:
  name: clusterlink-proxy-service
  namespace: clusterlink-system
spec:
  selector:
    app: clusterlink-proxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterlink-proxy
  namespace: clusterlink-system
  labels:
    app: clusterlink-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterlink-proxy
  template:
    metadata:
      labels:
        app: clusterlink-proxy
    spec:
      volumes:
        - name: proxy-config
          configMap:
            defaultMode: 420
            name: clusterlink-agent-proxy
      containers:
        - name: manager
          image: ghcr.io/kosmos-io/clusterlink/clusterlink-proxy:__VERSION__
          imagePullPolicy: IfNotPresent
          command:
            - clusterlink-proxy
            - --kubeconfig=/etc/clusterlink/kubeconfig
            - --authentication-kubeconfig=/etc/clusterlink/kubeconfig
            - --authorization-kubeconfig=/etc/clusterlink/kubeconfig
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /etc/clusterlink
              name: proxy-config
              readOnly: true
